# Site
#repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: J. Eckert
title: Gaming and Web3 Ecosystem and Operations Executive
email: contact@jeckert.net
# email_title: Email (Email title override)
#phone:
# phone_title: Phone (Phone title override)
website: https://links.jeckert.net
website_title: Links
resume: https://jeckert.net/resume
#resume_title: Resume (Resume title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: sargonas
github_username:  sargonas
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: sargonas
linkedin_username: jeckert
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
  #icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  #url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "G-Y5YP6KRQKP"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  16 Year veteran of the Video Game Industry, a long time gamer, hobbyist photographer, and avid maker... as well as Board Member for the Non-Profit running the Las Vegas Hackerspace/Makerspace [SYN Shop](https://synshop.org).

  A decade and a half experience spanning across many disciplines, including Operations, BizDev/Strategic Partnerships, Project Management, Developer Relations, Live Operations/IT, and Customer Service. (And I am versed *just* well enough in coding to be dangerous to myself!)

  For the last several years I have focused my efforts (and leveled up my skills) on helping startups grow from 10 to 100, focusing on the day-to-day business operations, building company culture, and establishing best practices and frameworks for success through the growing pains.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Chia Network
        sub_title: VP of Ecosystem Operations
        caption: May 2021 - October 2023
        link: https://chia.net
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          To quote a colleague: "Wrangler of cats, organizer of chaos, sharer of bad news, culture warrior/dissident, and mitigator of foot guns". More precisely, I crafted and defined Chia’s Ecosystem team, leading strategy and execution from the ground up across Developer Relations, Corporate Communications, User Community & Support. Additionaly a contributor to our thought Leadership, handled our internal Events, and was an ardent champion (or thorn in the side, depending on your point of view) of our Corporate Culture. I was also a member of Chia’s executive leadership team, shaping company-wide strategy and plans on our path to IPO. Sadly, an unforseen banking collapse in 2023 cut the journey short for I and the majority of my colleages.
        icon: fab fa-github  
      - layout: left
        title: Genvid Technologies
        sub_title: Director of Partnerships & Head of LA Office
        caption: Apr 2018 - May 2021
        link: https://genvidtech.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          As the overused saying goes, a man of many hats (as is common in early stage startups). Oversaw the day to day operations of our offices throughout California, as well as Strategic Partnerships efforts, and various random minutiae to keep the gears turning for the company throughout our various US offices during the exciting and challenging times of scaling the company from 15 people to 100. No trivial task, as we had to navigate the era of COVID in real time, as I lead the charge in taking us from a 5 employee, in-person regional outpost, to a fully remote regional organizaiton of several dozen, without the luxury of the many-years of learning we now have to lean on. Looking back retrospectively, I would have advocated for the now far more common "Chief of Staff" title that was relatively unknown at those times to best reflect my efforts.
      - layout: left
        title: Riot Games
        sub_title: Director of Developer Relations/3rd Party Ecosystem
        caption: Jan 2014 - Apr 2018
        link: https://riotgames.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Managing the Developer Relations Team, handling public-facing aspects of Riot’s API for League of Legends and (at the time) unannounced future titles, as well as various other 3rd party partnerships. Our team drove community engagement with the API, fostered and maintained partnerships with third-party developers, and worked with the API development team to guide it’s further development with player-focus in mind. I often said to people "If it is external to Riot Games, and has direct impact on our players/game without being related to esports, then it's somewhere on a spectrum of relevancy to my team(s)."
      - layout: left
        title: Honored
        sub_title: Co-Founder & CEO
        caption: Jun 2012 - Jan 2014
        link: https://gethonored.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Honored tried to provided tangible rewards for your proudest accomplishments in gaming, in the form of embroidered patches and other products to celebrate your accomplishments both in-game and within the greater gaming community. Pulling in data across various gaming platforms of player activity, you could earn badges and other rewards, as well as publisher-branded ones via partnerships. While ultimately unsucesfull, it's exciting to see that 10 years later this vision live on in success with projects like the Bungie Rewards merchandise program for Destiny 2.
        title: Electronic Arts
        sub_title: DevRel Account Manager - EA Online
        caption: Aug 2011 - Apr 2012
        link: https://ea.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Production layer between EA Global Online and various game development teams throughout EA and its partners. Responsible for making sure that the online needs of a game team, everywhere from digital publishing to online multiplayer components, are met by EA Online to successfully provide the online experience desired at launch and post-ship.
      - layout: left
        #title: Electronic Arts
        sub_title: Digitial Publishing Manager - EA Online/Origin
        caption: Apr 2011 - Aug 2011
        link: https://origin.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oversaw documentation for internal publishing guidelines for EA’s online platform, Origin. Also responsible for assisting with the digital publishing of various EA titles on the Origin platform.
      - layout: left
        #title: Electronic Arts
        sub_title: Compliance/Certification Project Lead
        caption: Nov 2009 - Mar 2011
        link: https://ea.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Project Lead for select titles built by EA-Redwood Shores studios for Compliance and Certification approval. (Sims, Visceral studios, EA Partners, etc). I take great pride is my near-perfect 1st Pass success rate at the big 3, *including* the famously high bar set by Nintendo!
      - layout: left
        #title: Electronic Arts
        sub_title: Operations Manager - Rupture/EA Online
        caption: Oct 2007 - Jun 2009
        link: https://ea.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
           Managed IT systems and general Ops & DevOps for the EA Atlanta and later Rupture (EA SF) divisions, handling widows and linux systems, general networking, various server and DB applications, and project management and production coordination.
      - layout: left
        title: Super Computer International (now EA)
        sub_title: Operations Manager
        caption: Jun 2006 - October 2007
        link: https://playlinc.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Held dual roles (as one does in a 12 person startup) as IT administrator/Ops manager, as well as community management for the development of Playlinc. Continued on under EA after our acquisition by them in October 2007
      - layout: left
        title: World Series of Video Games
        sub_title: Network administrator
        caption: 2005 - 2007
        link: https://wsvg.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          One of a team of Network Administrators for the WSVG events held around the world from 2005 to 2007. Specialized in putting together an enterprise class network for competitive gaming setupsand BYOC lans in only a matter of a few days for each event.
      - layout: left
        title: ASUS Technologies
        sub_title: Support Manager
        caption: Jun 2004 - Jun 2006
        link: https://asus.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Support tech and systems testing/diagnostic specialist. Also specialized in Video hardware trouble shooting and benchmark testing.
      - layout: left
        title: Kastle Systems
        sub_title: Systems Administrator
        caption: Jul 2003 - Jun 2004
        link: https://kastle.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Operations Programmer, office tech support and Systems Administrator for the Chicago regional office.
      - layout: left
        title: Express Technologies (Now Hosting.com)
        sub_title: Customer Service Manager
        caption: Mar 2002 - Jul 2003
        link: https://hosting.com
        #quote: >
          #Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Customer Service rep, Tech Support, and Abuse Administrator for an industry leading webhost.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Rival Peak
        sub_title: Genvid
        link: https://rivalpeak.com/
        #link_text: Link Text
        #additional_links:
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: >
        caption: >
          The first experimental, Massively Interactive Live Entertainment (MILE) reality show.
        description: |
          <div style="text-align: center;"><img src="images/rivalpeak.jpg" width="400"></div>
      - layout: left
        border: weak
        title: League of Legends
        sub_title: Riot Games
        link: https://leagueoflegends.com/
        caption: >
          League of Legends, the Riot API, and various other related projects over 4 years.
        description: |
          <div style="text-align: center;"><img src="images/lol.jpg" width="400"></div>
      - layout: left
        border: weak
        title: Honored
        link: https://gethonored.com/
        caption: >
          Real, tangible rewards for your gaming accomplishments!
        description: |
          <div style="text-align: center;"><img src="images/honored.png" width="400"></div>
      - layout: left
        border: weak
        title: Battlefield 3 & 4
        sub_title: EA Games
        link: https://battlefield.com/
        caption: >
          The preeminent, most realistic, modern FPS shooter franchise.
        description: |
          <div style="text-align: center;"><img src="images/battlefield-3.jpg" width="400"></div>
      - layout: left
        border: weak
        title: |
          Star Wars: the old Republic
        sub_title: EA Games
        link: https://swtor.com/
        caption: >
          A ground-breaking MMO set in the Star Wars universe, 10,000 years before the movies.
        description: |
          <div style="text-align: center;"><img src="images/swtor.jpg" width="400"></div>
      - layout: left
        border: weak
        title: Origin
        sub_title: EA Games
        link: https://origin.com/
        caption: >
          EA's digital distribution platform from 2012-2022.
        description: |
          <div style="text-align: center;"><img src="images/origin.png" width="400"></div>
      - layout: left
        border: weak
        title: Dead Space 2
        sub_title: EA Games
        link: https://deadspace.com/
        caption: >
          Survival horror game by Visceral Games, a studio within EA.
        description: |
          <div style="text-align: center;"><img src="images/deadspace2.jpg" width="400"></div>
      - layout: left
        border: weak
        title: Rockband 3
        sub_title: EA Games
        link: https://en.wikipedia.org/wiki/Rock_Band_3
        caption: >
          2010 rythim game sensation, created by Harmonix and published by EA.
        description: |
          <div style="text-align: center;"><img src="images/rockband3.webp" width="400"></div>
      - layout: left
        border: weak
        title: Rupture
        sub_title: EA Games
        link: https://en.wikipedia.org/wiki/Rupture_(social_networking)
        caption: >
          Social networking platform founded by Shawn Fanning (founder of Napster), designed to share gamers' individual profiles to a communal space.
        description: |
          <div style="text-align: center;"><img src="images/rupture.jpg" width="400"></div>
      - layout: left
        border: weak
        title: The WSVG
        link: https://en.wikipedia.org/wiki/World_Series_of_Video_Games
        caption: >
          An annual international esports competition, with competitions in six different games held around the world culminating in a finals brodacast on primetime TV. 
        description: |
          <div style="text-align: center;"><img src="images/wsvg.jpg" width="400"></div>
  - title: Media
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: INTERVIEW - J. Eckert of Genvid
        sub_title: The Esports Observer
        link: https://archive.esportsobserver.com/interview-j-eckert-genvid/
        link_text: https://esportsobserver.com/interview-j-eckert-genvid/
        #additional_links:
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: >
        caption: >
          INTERVIEW: J. Eckert, Genvid – “We’re Trying to Give Studios Tools That Redefine What It Means to Have a Game Streamed”
        description: |
          <div style="text-align: center;"><img src="images/eso-article.png" width="400"></div>
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Brewing Up A Conversation Podcast - J. Eckert
        sub_title: 90 Minute podcast interview from summer of 2023
        link: https://www.youtube.com/watch?v=SuVdQ-_uBo4
        link_text: https://www.youtube.com/watch?v=SuVdQ-_uBo4
        #additional_links:
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
            #icon: fab fa-github
            #url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #quote: >
        caption: >
          INTERVIEW: J. Eckert - "Life is a compounding journey"”
        description: |
          <div style="text-align: center;"><img src="images/brewing.png" width="400"></div>
  #- title: Education
    #layout: list
    #content:
      #- layout: top-right
        #title: Institution name
        #sub_title: Qualifications (eg. BA Performing Arts)
        #caption: Date Range (eg. 2016 - 2019)
        #quote: >
          #Short institution or course description (optional)
        #description: | # this will include new lines to allow paragraphs
          #Description of qualification
  #- title: A Little More About Me
    #layout: text
    #content: | # this will include new lines to allow paragraphs
      #This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      #Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]