---
name: Link checker
on:
  push:
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check all links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "_config.yaml"
          timeout: 10000
          #linksToSkip: ""
          markdown: false
